[project]
name = "legal-ai-rag"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "langchain>=1.2.10",
    "langchain-community>=0.4.1",
    "unstructured[pdf]>=0.20.2",
    "langchain-text-splitters>=0.3.6",
]
